### ISSUE TITLE
image_template not working

### ISSUE THREAD

**Issue by martinr63** [ExperienceLovelace/lovelace-floorplan#16]
when I try to use an image_template for a window, the path of the entinity svg is removed and a new path is inserted as a very small icon on the left border of the floorplan.

```
cards:
    - type: 'custom:floorplan-card'
      config:
        image: /local/floorplan/bilder/haus.svg
        stylesheet: /local/floorplan/css/haus.css?v=1.1.14
        rules:
         - entities:
             - binary_sensor.fensterkontakt_bad_contact
           image_template: '/local/floorplan/bilder/fenster_${entity.state}.svg'
```

**Comment by matt-shepherd** [comment]
I had this same issue..  my solution was to place a simple rect inside the root of the floorplan SVG with the entity ID.

**Comment by martinr63** [comment]
Hi, I can confirm your solution. This should be added in the docs

**Comment by koldogut** [comment]
Hi all, sorry but I'm a bit newbee. Is it something similar to this?? I've tried almost everything and double checked SVG format, size, position, etc, but I'm not able to center rooms on the floorplan. Thet are unscaled and moved to the right upper corner. ¿Any ideas? here you are the code

      - config:
          image: /local/floorplan/planta_baja.svg?v=1.1.15
          log_level: error
          more_info: true
          # panel: true
          rules: 
           - action:
              service: homeassistant.toggle
             element: light.terraza
             entity: light.terraza
             image_template: '/local/floorplan/terraza_${entity.state}.svg'
             state: image
           - action:
              service: homeassistant.toggle
             element: light.salon
             entity: light.salon
             image_template: '/local/floorplan/salon_${entity.state}.svg'
             state: image
           - action:
              service: homeassistant.toggle
             element: light.cocina
             entity: light.cocina
             image_template: '/local/floorplan/cocina_${entity.state}.svg'
             state: image
           - action:
              service: homeassistant.toggle
             element: light.estudio
             entity: light.estudio
             image_template: '/local/floorplan/estudio_${entity.state}.svg'
             state: image
        type: 'custom:floorplan-card'

![My_Floorplan](https://user-images.githubusercontent.com/43078880/76172395-a2593c80-6195-11ea-91d8-1ca5946cfd58.GIF)

**Comment by OzGav** [comment]
This is ages old but I don't believe you are using floorplan correctly here. Instead of trying to load a new image using image_template you generally put the "lights on" image directly into your main SVG and then you use CSS classess to show or hide that image. For example:

```
            - action:
                service: light.toggle
              entities:
                - light.main_toilet
              name: Lights
              states:
                - class: room-light-fadeout
                  state: 'off'
                - class: room-light-fadein
                  state: 'on'
```
