### ISSUE TITLE
Support having "groups" without "entities"

### ISSUE THREAD

**Issue by LordMike** [ExperienceLovelace/lovelace-floorplan#38]
If I set a rule with a `groups`, but no `entities`, I get an error. As a workaround, I do the following:

```yaml
          rules:
            - action:
                service: homeassistant.toggle
              entities: [] <-- notice the empty entities
              groups:
                - group.lights_all
              states:
                - class: light-off
                  state: 'off'
                - class: light-on
                  state: 'on'
```

I think these lines need to be altered.

https://github.com/pkozul/lovelace-floorplan/blob/40d8897e0bd6bd3fb1405fcff65530dd873b2daf/www/floorplan/lib/floorplan.js#L1381-L1385
