### ISSUE TITLE
Full Screen FloorPlan

### ISSUE THREAD

**Issue by TaviTav** [ExperienceLovelace/lovelace-floorplan#4]
I think it should be mentioned that if you want your floor plan card to have the width of the screen you need to add "panel: true" before "cards:". Example
```
  panel: true
  cards:
    - config:
        image: /local/floorplan/examples/simple/simple.svg?v=1.1.14
        rules:
          - entities:
etc, etc.
```

**Comment by KKnishev** [comment]
Add this info to readme.md please, very helpfull!

**Comment by bartplessers** [comment]
cool!. Is there also an option "fit". So the image will always fit? 
if you set 
panel: true
and the height of the image is large, the width will fit on the browser estate, but you still have to scroll down to see the whole image...

kind regards,
B

**Comment by JazekerXX** [comment]
> cool!. Is there also an option "fit". So the image will always fit?
> if you set
> panel: true
> and the height of the image is large, the width will fit on the browser estate, but you still have to scroll down to see the whole image...
> Also very usefull if you want a mobile interface. On PC: x>y, on mobile: y>x
> 
> kind regards,
> B

I would like that option too!
I have the same issue that my height is too high and thus you need to scroll down.
maybe they can add options like aspect-ratio: or height:

**Comment by kingtao1024** [comment]
This is a good suggestion！

> cool!. Is there also an option "fit". So the image will always fit?
> if you set
> panel: true
> and the height of the image is large, the width will fit on the browser estate, but you still have to scroll down to see the whole image...
> Also very usefull if you want a mobile interface. On PC: x>y, on mobile: y>x
> 
> kind regards,
> B

This is a good suggestion！

**Comment by KKnishev** [comment]
Hi there, here's a my solution for "full screen" with [thomasloven/lovelace-card-mod](https://github.com/thomasloven/lovelace-card-mod)
```
    cards:
      - type: custom:floorplan-card
        style: |
          ha-card { width: 96%; position: absolute; top: 0; left: 2%; }
```
